### ISSUE TITLE
do we need to resize image from the phone camera first?

### ISSUE THREAD

**Issue by duyhtq** [sh1r0/caffe-android-demo#11]
looking at your demo code.  it looks like you take the picture directly from the phone camera and send it to caffe to predict.  in my case, the image size from my camera on nexus 6 is 4160 x 3120, but the crop size is only specified as 227.

so how does this work?  does caffe automatically resize the image from 4160 x 3120 to something smaller?  

if there is no resize, how does the crop of 227 happens?  i assume that's 227 x 227.  is that in the middle of the image?  

my concern is that if it's in the middle and there is no resize, then 227 x 227 is a really small part of the entire image of 4160 x 3120.

any comment is much appreciated.

```
10-28 15:43:55.966  26041-26041/com.sh1r0.caffe_android_demo D/MainActivity﹕ /storage/emulated/0/Pictures/Caffe-Android-Demo/IMG_20151028_154348.jpg
10-28 15:43:55.966  26041-26041/com.sh1r0.caffe_android_demo D/MainActivity﹕ 4160
10-28 15:43:55.966  26041-26041/com.sh1r0.caffe_android_demo D/MainActivity﹕ 3120
```

```
transform_param {
    crop_size: 227
    mean_value: 104
    mean_value: 117
    mean_value: 123
    mirror: false
}
```

**Comment by duyhtq** [comment]
just found this.  does that mean all images are resized to 256 x 256 before prediction?  for example, in my case, the phone original image 4160 x 3120 is resized to 256 x 256.  and then it takes a crop in the middle 227 x 227.  and then run the prediction on the 227 x 227 image?

```
int CaffeMobile::test(string img_path) {
	CHECK(caffe_net != NULL);

	Datum datum;
	CHECK(ReadImageToDatum(img_path, 0, 256, 256, true, &datum));
	const shared_ptr<MemoryDataLayer<float>> memory_data_layer =
		static_pointer_cast<MemoryDataLayer<float>>(
			caffe_net->layer_by_name("data"));
	memory_data_layer->AddDatumVector(vector<Datum>({datum}));

	vector<Blob<float>* > dummy_bottom_vec;
	float loss;
	clock_t t_start = clock();
	const vector<Blob<float>*>& result = caffe_net->Forward(dummy_bottom_vec, &loss);
	clock_t t_end = clock();
	LOG(DEBUG) << "Prediction time: " << 1000.0 * (t_end - t_start) / CLOCKS_PER_SEC << " ms.";

	const float* argmaxs = result[1]->cpu_data();
	for (int i = 0; i < result[1]->num(); i++) {
		for (int j = 0; j < result[1]->height(); j++) {
			LOG(INFO) << " Image: "<< i << " class:"
			          << argmaxs[i*result[1]->height() + j];
		}
	}

	return argmaxs[0];
}
```

**Comment by sh1r0** [comment]
Yes. These questions are more related to the Caffe core rather than this demo app. If you are curious about the underlying implementation, you can refer to [Caffe](https://github.com/BVLC/caffe) repository.
