### ISSUE TITLE
Failed to parse NetParameter file

### ISSUE THREAD

**Issue by zhenghuitian** [sh1r0/caffe-android-demo#13]
I use your demo and try to run in eclipse, but I got an error that : A/native(21720): upgrade_proto.cpp:75 Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: /sdcard/caffe_mobile/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel

I don't change anything in your code. So what should I do to solve the problem?

By the way, I check the code and find it created on 3/26/15.

Thank you for your help and your code.

**Comment by sh1r0** [comment]
Sorry, I've never tried to run this project using eclipse (as this is basically a android studio project). Did you put everything required into the device yet (https://github.com/sh1r0/caffe-android-demo#quick-start)?

**Comment by zhenghuitian** [comment]
I am sure that I have done the requirements that your suggest at the project. And I can find the file in my phone in the correct path. The error happened while the  function caffeMobile.loadModel() is called. But this function is a native function and I can't debug it.

By the way, I am not familiar with android. Would you tell me what tool you use to run this project?

Thank you for your help.

**Comment by sh1r0** [comment]
As I said, this is a android studio project (http://developer.android.com/sdk/).

**Comment by zhenghuitian** [comment]
I will try it. Thank you.

**Comment by jimmod** [comment]
I tried with Android Studio and got similar error:
22608-22608/com.sh1r0.caffe_android_demo A/native: upgrade_proto.cpp:68 Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /sdcard/caffe_mobile/bvlc_reference_caffenet/deploy.prototxt

The file exists in the phone, I also checked it if the app can access by checking result of File.exists

**Comment by jimmod** [comment]
Solve it with use the previous deploy.prototxt file, the deploy.prototxt that pushed on Feb 26, 2016 is not compatible. My guess since the caffe lib so used is also the old one, they changed the parsing implementation on the latest caffe lib

**Comment by sh1r0** [comment]
@jimmod Thanks for your information, input data were switched to `Input` layers in https://github.com/BVLC/caffe/commit/2cc3844cb2a4a72de10d321781dc8f994bef95c7. I'll fix it asap.

**Comment by sh1r0** [comment]
Solved in https://github.com/sh1r0/caffe-android-demo/commit/a5f9d854b9578a0bfd3c50c26cba1f55e2823af0.
