### ISSUE TITLE
Error when I try to configure the next repository: https://github.com/BVLC/caffe.git 

### ISSUE THREAD

**Issue by fh127** [sh1r0/caffe-android-demo#14]
Error when I try to configure the next repository: https://github.com/BVLC/caffe.git 

in the command: ./scripts/download_model_binary.py models/bvlc_reference_caffenet/

launch the next error:

     Traceback (most recent call last):
      File "./scripts/download_model_binary.py", line 5, in <module>
      import yaml

**Comment by sh1r0** [comment]
`pip install pyyaml` could solve your problem. And if you have problems about caffe, you might want to check https://groups.google.com/forum/#!forum/caffe-users.
