### ISSUE TITLE
How to use “getConfidenceScore”？

### ISSUE THREAD

**Issue by ariexhyx** [sh1r0/caffe-android-demo#16]
0.3134 - "n02123045 tabby, tabby cat" 0.2380 - "n02123159 tiger cat"0.1235 - "n02124075 Egyptian cat" 0.1003 - "n02119022 red fox

I would like to show probabilities above,instead of labels.And I am a newbie so that I don't know how to use "getConfidenceScore".
can anybody help me？Many thanks.

private class CNNTask extends AsyncTask<String, Void, Integer> {
        private CNNListener listener;
        private long startTime;

        public CNNTask(CNNListener listener) {
            this.listener = listener;
        }

        @Override
        protected Integer doInBackground(String... strings) {
            startTime = SystemClock.uptimeMillis();
            return caffeMobile.predictImage(strings[0])[0];
        }

        @Override
        protected void onPostExecute(Integer integer) {
            Log.i(LOG_TAG, String.format("elapsed wall time: %d ms", SystemClock.uptimeMillis() - startTime));
            listener.onTaskCompleted(integer);
            super.onPostExecute(integer);
        }
    }

**Comment by sh1r0** [comment]
Please refer to the [source](https://github.com/sh1r0/caffe/blob/cmake_android/android/caffe_mobile.cpp#L193-L223) for details. Generally, it simply returns the raw output of network.
