### ISSUE TITLE
Not an issue per se: Why is CaffeMobile::SetMean used? How to manipulate it to get better result if at all possible?

### ISSUE THREAD

**Issue by rivaldo4t** [sh1r0/caffe-android-demo#17]
Kindly let me know what this function does.

**Comment by sh1r0** [comment]
As name tells, set mean values for mean subtraction. And also, [code](https://github.com/sh1r0/caffe/blob/cmake_android/android/caffe_mobile.cpp#L84-L125) tells you the truth.
Thanks.

**Comment by rivaldo4t** [comment]
A little weak on the concepts here. Why is mean subtraction required in evaluation of a net?

**Comment by sh1r0** [comment]
IMHO, this is not wired for following the same preprocessing protocol as in the training.

**Comment by sh1r0** [comment]
Note: the "mean" here is not from your test image, it's the one used in the model training.

**Comment by rivaldo4t** [comment]
Yes I figured that. The mean values are set to some seemingly random values in the demo code. 

float[] meanValues = {104, 117, 123};
caffeMobile.setMean(meanValues);

This is what does not make sense to me. What are these values.

**Comment by sh1r0** [comment]
https://github.com/BVLC/caffe/blob/master/models/bvlc_reference_caffenet/train_val.prototxt

**Comment by rivaldo4t** [comment]
Ok; not random. Still not clear on the WHY part.

**Comment by rivaldo4t** [comment]
Is it because we have trained the network on transformed images (mean subtracted) by these mean values and we must transform the test image in the same way during the evaluation phase?

**Comment by sh1r0** [comment]
Exactly.

**Comment by rivaldo4t** [comment]
Okay, thanks.
