### ISSUE TITLE
could anyone help me solving this problem

### ISSUE THREAD

**Issue by nasirrahim** [sh1r0/caffe-android-demo#19]
http://stackoverflow.com/questions/36976793/impelmenting-caffe-model-in-android

**Comment by sh1r0** [comment]
Sorry, I did not get your idea. What exactly is "implement" you mean here? Basically, the demo app is based on `bvlc_reference_caffenet`.

**Comment by nasirrahim** [comment]
Thank you  for your reply
simply i just want to run your code on mobile . i follow the same procedure
that you have mentioned. i create a new folder in SD card by the name of
caffe_mobile and then copy bvlc_reference_caffenet. but it throws
exception. but when i copy  bvlc_googlenet.caffemodel to same folder so it
works fine . why it is giving me this exception with that model

upgrade_proto.cpp:79 Check failed: ReadProtoFromTextFile(param_file,
param) Failed to parse NetParameter file:
/storage/sdcard1/caffe_mobile/bvlc_reference_caffenet/deploy.prototxt

**Comment by sh1r0** [comment]
Apparently, the error message is about `deploy.prototxt`. Did you put the right [one](https://github.com/BVLC/caffe/blob/master/models/bvlc_reference_caffenet/deploy.prototxt) beside the model binary?

**Comment by nasirrahim** [comment]
yes exactly i put that file in that folder but it converts to some symbols
when i run my code and check this file in notepad

**Comment by sh1r0** [comment]
How? `adb push`?

**Comment by nasirrahim** [comment]
and it does not change in case of  googlenet.caffemodel

**Comment by nasirrahim** [comment]
i copy it and past it in text file and save it to deploy.prototxt and copy
it to that folder

**Comment by sh1r0** [comment]
Why not just download that file and `adb push` it? Could you have a try?

**Comment by nasirrahim** [comment]
ok i try it now.
