### ISSUE TITLE
caffe android demo app showed error

### ISSUE THREAD

**Issue by hubino** [sh1r0/caffe-android-demo#2]
I would like to use Caffe builded version in my Android application.for this purpose I downloaded https://github.com/sh1r0/caffe-android-demo demo project from this given link. But while run the corresponding downloaded project in Android Studio It showed the error as below
`03-26 14:46:35.697    2800-3042/com.sh1r0.caffe_android_demo A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 3042 (AsyncTask #1)`  please help me to run the demo application successfully.

**Comment by sh1r0** [comment]
I updated the jni libs and the related part in this project. Please follow README to get correct models and try to re-build this project. Everything should be fine :)

Thanks.

**Comment by hubino** [comment]
Sh1r0,
I have downloaded your recent code which contains some latest commits. It is running successfully without any issue what I mentioned before.
But here I have some doubts  
 `return caffeMobile.predictImage(strings[0]);`
The `predictImage(strings[0])` method always returning a constant `Integer` value `672` 
 `IMAGENET_CLASSES[672] = mountain tent`
So the `mountain tent` String is shown for all the images either captured from `Camera` or selected from `Gallery`

steps I followed to run the **Demo Project**
1.https://github.com/sh1r0/caffe-android-demo downloaded a project from above link
2.Created a folder with the name `caffe_mobile` in device `SdCard`
3. Copied the `bvlc_reference_caffenet` folder from this link https://github.com/sh1r0/caffe/tree/mobile/models  and pasted into `caffe_mobile` folder
4.Cleaned  and run the code.

**Comment by sh1r0** [comment]
Sorry, but as far as I have tested on several phones, I did not encounter such problems. Could you provide some more details? Or you can try this caffe example [image](https://raw.githubusercontent.com/BVLC/caffe/master/examples/images/cat.jpg), the result is likely to be `tabby, tabby cat`.

**Comment by hubino** [comment]
Sh1r0,

As I didn't include `bvlc_reference_caffenet.caffemodel`  file in my `bvlc_reference_caffenet` folder, I kept on getting answers as only "mountain tent" for all the results.After that
I had download `bvlc_reference_caffenet.caffemodel`file and included in `bvlc_reference_caffenet` folder after these processes It  work's great. Thanks for your support to execute the project.

I would like to use caffe in my Android project,for this purpose I will send some input to  `Caffe` and It will return results for that sent input.so I need to know about what are the methods used in built `so`s
`libcaffe.so`
`libcaffe_jni.so`

I would like to know what are the method used by you,so that there will be no use for me to go on with the building process once again.

**need information about Caffe IOS framework**
Is there a demo application to execute the caffe framework in IOS ?
Or else can you please provide the build steps to create the framework or .a file to execute the caffee framework with sample ?

**Comment by sh1r0** [comment]
`libcaffe.so` is solely the ported (pruned) Caffe. `libcaffe_jni.so` simply wraps some simple interfaces to use Caffe lib, and might not always suit for your needs. You can take a look at these 3 files, [caffe_jni.cpp](https://github.com/sh1r0/caffe-android-lib/blob/master/caffe-mobile/jni/caffe_jni.cpp), [caffe_mobile.hpp](https://github.com/sh1r0/caffe-android-lib/blob/master/caffe-mobile/jni/caffe_mobile.hpp) and [caffe_mobile.cpp](https://github.com/sh1r0/caffe-android-lib/blob/master/caffe-mobile/jni/caffe_mobile.cpp), for more information.

Sorry, I don't know if there is any existed ported Caffe for iOS. But for static libs (.a), this [Makefile](https://github.com/sh1r0/caffe/blob/mobile/Makefile.mobile) might give you some clues, and likely, you'll need iOS cross compliation toolchain.

**Comment by hubino** [comment]
Okay thanks for your valuable reply.

**Comment by hubino** [comment]
Sh1r0,

I need to know whether `these(set_mode,SetDevice,set_phase,Net,Layer,MemoryDataLayer)` are the `Caffe` methods are there in `libcaffe.so`. So please confirm it.

Thanks

**Comment by sh1r0** [comment]
Yes, those are Caffe methods. Custom methods used for jni lib are at these 3 files, [caffe_jni.cpp](https://github.com/sh1r0/caffe-android-lib/blob/master/caffe-mobile/jni/caffe_jni.cpp), [caffe_mobile.hpp](https://github.com/sh1r0/caffe-android-lib/blob/master/caffe-mobile/jni/caffe_mobile.hpp) and [caffe_mobile.cpp](https://github.com/sh1r0/caffe-android-lib/blob/master/caffe-mobile/jni/caffe_mobile.cpp), as I mentioned before.
Thanks.

**Comment by hubino** [comment]
Thanks
