### ISSUE TITLE
Fatal signal 6 (SIGABRT) on Samsung Galaxy Note Edge

### ISSUE THREAD

**Issue by sladomic** [sh1r0/caffe-android-demo#20]
Hi

I use your example in my face recognition project. The bvlc model works on my Sony Xperia Z3 Compact. But the VGG Face Descriptor model (which is twice as big) needs too much RAM, so I needed to switch to another phone with more memory.

Now I got the problem, that on the Samsung Galaxy Note Edge I cannot get further than this point:

I/native: upgrade_proto.cpp:43 Attempting to upgrade input file specified using deprecated transformation parameters: /storage/emulated/0/Pictures/facedetection/data/VGG/bvlc_reference_caffenet.caffemodel
I/native: upgrade_proto.cpp:46 Successfully upgraded file specified using deprecated data transformation parameters.
W/native: upgrade_proto.cpp:48 Note that future Caffe releases will only support transform_param messages for transformation fields.
I/native: upgrade_proto.cpp:52 Attempting to upgrade input file specified using deprecated V1LayerParameter: /storage/emulated/0/Pictures/facedetection/data/VGG/bvlc_reference_caffenet.caffemodel
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 6635 (Thread-2990)

I first thought that the architecture (arm64-v8a vs. armeabi-v7a) could cause the issue but your demo works (well it runs out of memory while rendering but the prediction works).

So it should be another issue. Do you have any ideas?

Thanks,
Michael

**Comment by sh1r0** [comment]
Could you provide more details, for example, what kind of model you use or how to reproduce?
Thanks.

**Comment by sladomic** [comment]
I want to use the VGG Face Descriptor model "http://www.robots.ox.ac.uk/~vgg/software/vgg_face/" but since it's too large for my first device (Sony) I tried the code on another device (Samsung). On the first device everything works fine (your bvlc model and the other model mentioned above) and just runs out of memory at some point. On the Samsung however neither model works. It always crashes at this point "upgrade_proto.cpp:52 Attempting to upgrade input file specified using deprecated V1LayerParameter". 

Your demo however works on the Samsung device which is strange as we use the same model. Here's how I try to load the model:

`public class VGGFaceDescriptor implements Recognition {
    CaffeMobile caffe;
    SupportVectorMachine svm;
    FileHelper fh;

    static {
        System.loadLibrary("caffe");
        System.loadLibrary("caffe_jni");
    }

    public VGGFaceDescriptor(int method) {
        fh = new FileHelper();
        **String dataPath = fh.VGG_PATH;
        caffe = new CaffeMobile();
        caffe.setNumThreads(4);
//        caffe.loadModel(dataPath + "VGG_FACE_deploy.prototxt",
//                dataPath + "VGG_FACE.caffemodel");
        caffe.loadModel(dataPath + "deploy.prototxt",
                dataPath + "bvlc_reference_caffenet.caffemodel");**

        float[] meanValues = {104, 117, 123};
        caffe.setMean(meanValues);
        svm = new SupportVectorMachine(method);
    }`

**Comment by sladomic** [comment]
Hi

I just tried both models on a Samsung Galaxy S6 and they worked fine.

I've no idea what the problem with the Note Edge is. But it isn't that important anymore.

Thanks

**Comment by sh1r0** [comment]
Good to know. Thanks.
