### ISSUE TITLE
After initializing the network, the app stop without any prompt of error.

### ISSUE THREAD

**Issue by zazd** [sh1r0/caffe-android-demo#21]
In Run of studio:
$ adb shell am start -n "com.sh1r0.caffe_android_demo/com.sh1r0.caffe_android_demo.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Connected to process 12290 on device Galaxy_Nexus_API_22 [emulator-5554]
Connected to process 12290 on device Galaxy_Nexus_API_22 [emulator-5554]
Connected to process 12290 on device Galaxy_Nexus_API_22 [emulator-5554]
Connected to process 12290 on device Galaxy_Nexus_API_22 [emulator-5554]
Connected to process 12290 on device Galaxy_Nexus_API_22 [emulator-5554]
Application terminated.

In Android Monitor:
05-11 11:52:07.474 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 fc6 does not need backward computation.
05-11 11:52:07.474 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 pool5 does not need backward computation.
05-11 11:52:07.474 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 relu5 does not need backward computation.
05-11 11:52:07.474 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 conv5 does not need backward computation.
05-11 11:52:07.474 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 relu4 does not need backward computation.
05-11 11:52:07.475 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 conv4 does not need backward computation.
05-11 11:52:07.475 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 relu3 does not need backward computation.
05-11 11:52:07.475 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 conv3 does not need backward computation.
05-11 11:52:07.475 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 norm2 does not need backward computation.
05-11 11:52:07.475 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 pool2 does not need backward computation.
05-11 11:52:07.475 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 relu2 does not need backward computation.
05-11 11:52:07.475 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 conv2 does not need backward computation.
05-11 11:52:07.476 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 norm1 does not need backward computation.
05-11 11:52:07.497 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 pool1 does not need backward computation.
05-11 11:52:07.498 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 relu1 does not need backward computation.
05-11 11:52:07.499 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:230 conv1 does not need backward computation.
05-11 11:52:07.499 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:272 This network produces output prob
05-11 11:52:07.500 12630-12630/com.sh1r0.caffe_android_demo I/native: net.cpp:285 Network initialization done.
05-11 11:52:21.038 12630-12630/com.sh1r0.caffe_android_demo I/native: upgrade_proto.cpp:42 Attempting to upgrade input file specified using deprecated transformation parameters: /data/caffe_mobile/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
05-11 11:52:21.042 12630-12630/com.sh1r0.caffe_android_demo I/native: upgrade_proto.cpp:45 Successfully upgraded file specified using deprecated data transformation parameters.
05-11 11:52:21.042 12630-12630/com.sh1r0.caffe_android_demo W/native: upgrade_proto.cpp:47 Note that future Caffe releases will only support transform_param messages for transformation fields.
05-11 11:52:21.045 12630-12630/com.sh1r0.caffe_android_demo I/native: upgrade_proto.cpp:51 Attempting to upgrade input file specified using deprecated V1LayerParameter: /data/caffe_mobile/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel

after this, the app stops, and I can not find any prompt of error, so what happened? I run this demo is KVM.
Thank you!

**Comment by sh1r0** [comment]
I guess that you are running the demo app on an ARM-based emulator. If so, in my experience, I had some trials before but end up with failures, probably caused by OOM (out of memory) or something. IMHO, if you do not have a device, I recommend you to build [caffe-android-lib](https://github.com/sh1r0/caffe-android-lib) for x86_64 on your own and then run the app on a x86_64 emulator.

**Comment by zazd** [comment]
Thanks.I try it in the mobile phone and it words. However, I run it in the kvm because my target device is an ARM-V7 box, and its android api 19. But when I run the demo in it, it got the error :
       dlopen failed: cannot locate symbol "sigfillset" referenced by "libcaffe.so"...
but it words in the api 21/+.
I am now trying to solve this error. Thank you for your help.

**Comment by sh1r0** [comment]
As API level issues, please refer to https://github.com/sh1r0/caffe-android-lib/issues/39.
Thanks.

**Comment by zazd** [comment]
I have read it before. And I still hope to run it in api 19. I will try it by myself, thank you!
