### ISSUE TITLE
Application crashes at caffeMobile.loadModel()

### ISSUE THREAD

**Issue by ynpoornima** [sh1r0/caffe-android-demo#22]
Hi,
I'm facing issue when the call goes to caffeMobile.LoadModel(). Below is the fatal error popped up.

05-13 05:00:22.214 12017-12017/com.sh1r0.caffe_android_demo A/native: io.cpp:36 Check failed: fd != -1 File not found: /storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/deploy.prototxt
05-13 05:00:22.214 12017-12017/com.sh1r0.caffe_android_demo A/native: terminating.
05-13 05:00:22.214 12017-12017/com.sh1r0.caffe_android_demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 12017 (fe_android_demo)

Has anyone encountered the same issue?.

Files are present in sdcard and I confirmed by putting prints in JNI file and below is path shown.
05-13 05:00:22.213 12017-12017/com.sh1r0.caffe_android_demo I/caffe_jni: /storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
05-13 05:00:22.213 12017-12017/com.sh1r0.caffe_android_demo I/caffe_jni: /storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/deploy.prototxt

Note:
I have compiled the lib in https://github.com/sh1r0/caffe-android-lib for x86 platform.

Thanks in advance.

Regards,
Poornima

**Comment by sh1r0** [comment]
I built caffe-android-lib for x86 abi on the dev branch and tested on an x86 emulator (android api 22) without any problems. Which branch did you use? Would you like to retry on the latest dev branch of caffe-android-lib?
Thanks.

**Comment by sh1r0** [comment]
Any updates?

**Comment by belindanju** [comment]
Hi, I have also encountered the same app crashing issue on android API 23. 
I have compiled the lib in https://github.com/sh1r0/caffe-android-lib for arm platform on master branch.

05-19 00:31:06.284 2839-2839/com.sh1r0.caffe_android_demo A/caffe_jni: F0519 00:31:06.284315  2839 io.cpp:36] Check failed: fd != -1 (-1 vs. -1) File not found: /storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/deploy.prototxt
05-19 00:31:06.284 2839-2839/com.sh1r0.caffe_android_demo A/caffe_jni: terminating.
05-19 00:31:06.284 2839-2839/com.sh1r0.caffe_android_demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 2839 (fe_android_demo)

 Files do exist by checking through adb shell. Any ideas how to fix it?

**Comment by sh1r0** [comment]
Hi @belindanju, please refer to #41, thanks.

**Comment by belindanju** [comment]
@sh1r0 Thanks for the quick response. Manually granting permissions works! I overlooked it because the permission granting (> API 23) is commonly handled in the Android code itself. I should realized sooner that I was never prompted the permission dialogs.
