### ISSUE TITLE
caffe demo error with custom build caffe android library.

### ISSUE THREAD

**Issue by ravibanger-nd** [sh1r0/caffe-android-demo#23]
I am able to build and run the demo code caffe-android-demo with the armeabi-v7a caffe binary as part of the demo distribution. However when I try to build my own caffe-android-lib the demo fails with the output. 

upgrade_proto.cpp:68 Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /storage/6A60-09E3/caffe/models/bvlc_reference_caffenet/deploy.prototxt
 com.sh1r0.caffe_android_demo A/native: terminating.

The protobuf version as specified in the caffe-android-lib does not seem to parse the file deploy.prototxt file. I have confirmed that the file is available in the said location and the file descriptor is open. It is failing  when google::protobuf is trying to parse the file. 

Besides this I also tried to run the same cpp_classification example as given in the location http://caffe.berkeleyvision.org/gathered/examples/cpp_classification.html
and get the same error as above in the logcat. 

Does anyone know about this issue, and a way to overcome this?

**Comment by sh1r0** [comment]
Which branch of caffe-android-lib did you use? If you are on master, please refer to https://github.com/sh1r0/caffe-android-lib/issues/44.
Thanks.

**Comment by ravibanger-nd** [comment]
Thanks I was able to verify in the develop branch. And I see that you have updated the master also.
