### ISSUE TITLE
get an error  when changed the prototxt

### ISSUE THREAD

**Issue by zazd** [sh1r0/caffe-android-demo#24]
I can use the demo， but when I changed the net architecture(also changed the caffemodel) like：
 layer {
  name: "conv1_v"
  type: "Convolution"
  bottom: "data"
  top: "conv1_v"
  convolution_param {
    num_output: 8
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0.0
    }
    pad_h: 3
    pad_w: 0
    kernel_h: 7
    kernel_w: 1
    stride_h: 1
    stride_w: 1
  }
}
The demo failed，and show that：
                                                                    layer {
                                                                      name: "conv4_h"
                                                                      type: "Convolution"
                                                                      bottom: "conv4_v"
                                                                      top: "conv4"
                                                                      convolution_param {
                                                                        num_output: 384
                                                                        group: 2
                                                                        weight_filler {
                                                                          type: "gaussian"
                                                                          std: 0.01
                                                                        }
                                                                        bias_filler {
                                                                          type: "constant"
                                                                          value: 0
                                                                        }
                                                                        pad_h: 0
                                                                        
05-26 14:08:53.387 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 1216512
05-26 14:08:53.388 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 15814656
05-26 14:08:53.388 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 30412800
05-26 14:08:53.389 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 37863168
05-26 14:08:53.389 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 41588352
05-26 14:08:53.390 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 43140512
05-26 14:08:53.392 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 53074336
05-26 14:08:53.393 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 63008160
05-26 14:08:53.393 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 68076960
05-26 14:08:53.393 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 70611360
05-26 14:08:53.401 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 71205360
05-26 14:08:53.411 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 75006960
05-26 14:08:53.411 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 78808560
05-26 14:08:53.411 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 80786928
05-26 14:08:53.412 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 81776112
05-26 14:08:53.422 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 82033712
05-26 14:08:53.430 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 83022896
05-26 14:08:53.430 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 84012080
05-26 14:08:53.456 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 84527280
05-26 14:08:53.469 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 85186736
05-26 14:08:53.469 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 85846192
05-26 14:08:53.490 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 86361392
05-26 14:08:53.503 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 87020848
05-26 14:08:53.503 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 87680304
05-26 14:08:53.505 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 87803952
05-26 14:08:53.505 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 88133680
05-26 14:08:53.506 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 88463408
05-26 14:08:53.506 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 88587056
05-26 14:08:53.507 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 88916784
05-26 14:08:53.508 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 89246512
05-26 14:08:53.508 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 89259392
05-26 14:08:53.508 5263-5263/com.sh1r0.caffe_android_demo I/native: net.cpp:167 Memory required for data: 89308336

What happened？I changed the kernel size(pad and stride) not be square，and can run in PC caffe，but failed in your demo. Thank you for your help.

**Comment by sh1r0** [comment]
Any details?

**Comment by zazd** [comment]
@sh1r0 update. Sorry for my terrible browser

**Comment by sh1r0** [comment]
Did you build the project based on the latest commit (https://github.com/sh1r0/caffe-android-demo/commit/426e57cec9b7e2ed8795be533ef35316137f1a43)?

**Comment by zazd** [comment]
Yes, I words by using the latest vision of caffe-android-lib and demo.But I got a result that it cost me 10s to run a picture by the latest vision. however, 8s, using the previous version. Would you tell me why?

**Comment by sh1r0** [comment]
Does your problem still exist?
I guess the performance degradation is caused by one of OpenBLAS and glog, or both. I'll clarify later.

**Comment by zazd** [comment]
The problem was solved by using the latest vision of caffe-android-lib and demo. Thank you.
