### ISSUE TITLE
Integration with android Project #Failure   --  missing  headers

### ISSUE THREAD

**Issue by aliceresponde** [sh1r0/caffe-android-demo#25]
Hi,  How are  you?
I have an issue in my project and I was wondering if you could help me . 
I'm  trying  to  integrate your  libcaffe.so files for  each architecture **armeabi armeabi-v7a x86 arm64-v8a x86_64**  in own  jni folder 

Here is our Application.mk
`
APP_STL := gnustl_static
APP_CPPFLAGS :=  -std=c++11 -frtti -fexceptions
APP_ABI :=  armeabi armeabi-v7a x86 arm64-v8a x86_64
APP_PLATFORM := android-8
NDK_TOOLCHAIN_VERSION := 4.9`

We  load it in  the Android.mk 
`include $(CLEAR_VARS)
LOCAL_MODULE := caffe
LOCAL_SRC_FILES := ../caffe/$(TARGET_ARCH_ABI)/libcaffe.so
LOCAL_C_INCLUDES +=  include/boost  include/caffe include/gflagas include/glog include/google/protobuf 
include $(PREBUILT_SHARED_LIBRARY)`

I load the caffe module this way
`LOCAL_SHARED_LIBRARIES += caffe`

after  run  `ndk-build` we   get  the error message 
   missing **cblas.h**

then we  include openBlas headers from the official site

now  we  have  this error:

**jni/OpenBLAS/lapack-netlib/CBLAS/include/cblas.h:27:28: fatal error: cblas_mangling.h: No such file or directory
 #include "cblas_mangling.h"
**

The   question is : 

could  you  tell me which are  the  correct headers that we must to include to  make  it work. 

Thanks

**Comment by sh1r0** [comment]
Hi @aliceresponde, I've created a [sample](https://gist.github.com/sh1r0/0ee4b83addf06157f3f5bcfc9294a082) for using prebuilt caffe libs in a ndk project. The sample works for me to build caffe_jni with ndk-build.

**Comment by sh1r0** [comment]
Any updates?
