### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by czhang96** [sh1r0/caffe-android-demo#27]
Demo app crashes out of the box with no logcat errors. Last log is `upgrade_proto.cpp:52 Attempting to upgrade input file specified using deprecated V1LayerParameter: /sdcard/caffe_mobile/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel` 

Any help?

**Comment by sh1r0** [comment]
I guess it was an OOM (out of memory) issue. Please confirm that you are on the latest master branch and also refer to #20 and #21 .
Thanks.

**Comment by czhang96** [comment]
Thanks for the quick reply! I am on the latest master, I'll investigate those issues further soon. FYI, I am running this on a real device with 1 GB ram, I thought memory would not be an issue here but it seems like I'm wrong!

Thanks again

**Comment by czhang96** [comment]
Using smaller model (Squeezenet) solves the issue, thanks!
