### ISSUE TITLE
Problems running latest version on specific devices

### ISSUE THREAD

**Issue by mtngld** [sh1r0/caffe-android-demo#3]
I used the previous version (4140a53447b0b7f419bacbe0ff1dfa53ff1c08f8) of this demo on Samsung Note 1 (GT-N7000), everything worked fine.

After pulling the latest version (5a80ac6a14fe5a0b493ac8e20137c7bd14710f36) the app crashes while starting up.

What's more interesting is that the new version works fine on other devices (LG G3, Samsung S4)

Do you have any idea what changed between these commits that might have suce an affect?

Thanks

**Comment by sh1r0** [comment]
What's the android version on your Samsung Note 1 (GT-N7000)?

**Comment by mtngld** [comment]
Android version is 4.0.4,

The problem is probably related to the JNI libs, app crashes when calling loadModel

**Comment by sh1r0** [comment]
Did you update the models in your Samsung Note 1 as well?

**Comment by mtngld** [comment]
Yes, I ran adb push again after switching

**Comment by sh1r0** [comment]
Sorry, can you provide more details about the error? Or, does your phone have enough memory for loading a CaffeNet (probably needs 500mb or even more available RAM) ?

**Comment by mtngld** [comment]
The demo app just crash after loadModel, on the older version it worked fine (with initTest) so I guess my phone should be able to support it, at least the older version.

Is there any way to output the internal caffe log from the app?

**Comment by sh1r0** [comment]
Alright, I use a naive way to redirect native logs to android logcat. You now can see what happen in `loadModel()`. ;p

**Comment by mtngld** [comment]
OK, I ran the new version on both phones again,

Please take a look at the logs at:
- Samsung Note (Fails) - https://gist.github.com/mtngld/fc36f60b7dc8e8b43a39
- LG G3 (works) - https://gist.github.com/mtngld/9ee26edc94e7599d3d08

This is the same version (latest commit) and I pushed all model files again, just to be sure.

Looks to me like the problem is related to loading weights and upgradeing

**Comment by sh1r0** [comment]
Sorry, I just checked the 2 log files. It seemed that after the network initialization was done, the model loading stopped abruptly on your Samsung Note.
Please refer to [this](https://gist.github.com/mtngld/9ee26edc94e7599d3d08#file-lg-g3-log-works-L1307-L1310) and [this](https://gist.github.com/mtngld/fc36f60b7dc8e8b43a39#file-samsung-note-fails-L1396-L1419). The behaviours are coherent till the point which is highlighted. And actually, the `Error`s are actually not vital , while Caffe core use `ERROR` level to report (should be warnings).
I really have no idea what happened to your phone after the network initialization was done. All I can guess is that your phone ran out of  RAM at that time.

**Comment by sh1r0** [comment]
Sorry, I have no idea about the changes in the underlying implementation of the memory management in Caffe core, as I focus on the high level features (e.g., layers) only.

**Comment by mtngld** [comment]
Thanks, 

I guess it is related to some lower layer caffe memory issue, 

Thanks for your help, closing this issue
