### ISSUE TITLE
I repalace bvlc_reference_caffenet.caffemodel with my test.caffemodel, demo crashed

### ISSUE THREAD

**Issue by liuyi999111** [sh1r0/caffe-android-demo#31]
I had load my own modelProto, modelBinary. I use extractFeatures function to get result. but app crashed aboute tens of seconds later. this test.caffemodel works on Windows. I don't get any error log. if I can't use the libcaffe.so directly? What should I do to make my test model works?

**Comment by sh1r0** [comment]
If you did not get any error message, it was probably caused by out of memory. See also https://github.com/sh1r0/caffe-android-demo/issues/27.

**Comment by liuyi999111** [comment]
ok,thanks.
