### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by ktak199** [sh1r0/caffe-android-demo#33]
I'm trying another model but app crashes.
Error is below.
> 08-29 00:37:35.500 16776-17047/com.sh1r0.caffe_android_demo A/caffe_jni: F0829 00:37:35.500212 17047 syncedmem.hpp:25] Check failed: *ptr host allocation of size 568295424 failed
08-29 00:37:35.500 16776-17047/com.sh1r0.caffe_android_demo A/caffe_jni: terminating.
08-29 00:37:35.500 16776-17047/com.sh1r0.caffe_android_demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 17047 (AsyncTask #1)

I think that the cause is out of memory and I should modify deploy.prototxt such that the mini batch size.
How to modify batch size?

Thank you in advance.

**Comment by sh1r0** [comment]
Edit your deploy.prototxt and push back into your device, or you could use any editor app directly.

**Comment by ktak199** [comment]
Thank you @sh1r0 .
How to edit deploy.prototxt ?
Could you give me some sample ?

**Comment by sh1r0** [comment]
Are you familiar with caffe? Take [this](https://github.com/BVLC/caffe/blob/master/models/bvlc_reference_caffenet/deploy.prototxt#L6) as an example, the first `dim` in shape is for batch size.

**Comment by ktak199** [comment]
Thank you @sh1r0 .
I'll try it.
