### ISSUE TITLE
demo for other caffe networks

### ISSUE THREAD

**Issue by Stark123** [sh1r0/caffe-android-demo#36]
Hi,
How can we achieve a similar application for other caffe networks?

**Comment by sh1r0** [comment]
Hi @Stark123,

This project is no more than a basic demo app for [caffe-android-lib](https://github.com/sh1r0/caffe-android-lib), which aims at porting caffe to android. That is, as long as the model is supported by official caffe, it "should" be okay to be used via caffe-android-lib as well. You could go through this simple app first as an overview.

Thanks.

**Comment by sh1r0** [comment]
Could be reopened if needed.
