### ISSUE TITLE
Does this apply to googlenet training out of the model？

### ISSUE THREAD

**Issue by Marryli** [sh1r0/caffe-android-demo#37]
Please，I want to know whether this applies to googlenet model. I replace the model with the googlenet ,and I  encounter problems.

**Comment by sh1r0** [comment]
Yes, and you need both the corresponding deploy.prototxt and model binary.

**Comment by Marryli** [comment]
Thanks, I may be write the wrong file.But can you send me the deploy.prototxt about googlenet-v3?

2016-10-24 

declihuifang 



发件人：sh1r0 <notifications@github.com>
发送时间：2016-10-24 10:02
主题：Re: [sh1r0/caffe-android-demo] Does this apply to googlenet training out of the model？ (#37)
收件人："sh1r0/caffe-android-demo"<caffe-android-demo@noreply.github.com>
抄送："Marryli"<Declihuifang@163.com>,"Author"<author@noreply.github.com>

Yes, and you need both the corresponding deploy.prototxt and model binary.

**Comment by sh1r0** [comment]
Sorry, I do not have either the model or the prototxt file.

**Comment by Marryli** [comment]
Thank you! I have done it.

2016-10-27 

declihuifang 



发件人：sh1r0 <notifications@github.com>
发送时间：2016-10-26 09:20
主题：Re: [sh1r0/caffe-android-demo] Does this apply to googlenet training out of the model？ (#37)
收件人："sh1r0/caffe-android-demo"<caffe-android-demo@noreply.github.com>
抄送："Marryli"<Declihuifang@163.com>,"Author"<author@noreply.github.com>

Sorry, I do not have either the model or the prototxt file.
