### ISSUE TITLE
Can't load the libcaffe.so??

### ISSUE THREAD

**Issue by wuqiangch** [sh1r0/caffe-android-demo#38]
Caused by: java.lang.UnsatisfiedLinkError: Couldn't load caffe: findLibrary returned null
                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                                     at java.lang.System.loadLibrary(System.java:535)
I just download your project and run it .

**Comment by sh1r0** [comment]
Did you modify anything?

**Comment by wuqiangch** [comment]
Nothing,
![image](https://cloud.githubusercontent.com/assets/7983007/19710041/de7e7952-9b5d-11e6-8401-dbe9440f0bb0.png)

**Comment by sh1r0** [comment]
A fresh clone, then build & run?

**Comment by wuqiangch** [comment]
Yes, I installed it on my phone,but can't open the application.

**Comment by sh1r0** [comment]
What's your arch?

**Comment by litianyuan1111** [comment]
i use this project ，the same error， how can i get deploy.prototxt"

**Comment by sh1r0** [comment]
@litianyuan1111 Please tell me arch and android version of your device. And [Readme](https://github.com/sh1r0/caffe-android-demo#quick-start) shows you how to get basic stuff.

**Comment by sh1r0** [comment]
@wuqiangch Any updates?

**Comment by wuqiangch** [comment]
@sh1r0 I am so busy . I will try it later .

**Comment by sh1r0** [comment]
@wuqiangch Any updates? Or, should be closed.

**Comment by innocentmujahid** [comment]
I have 9.0 getting same error  couldn't find "libcaffe.so"
