### ISSUE TITLE
there is not a mini batch parameter in deploy.proto.

### ISSUE THREAD

**Issue by wumangxing1990** [sh1r0/caffe-android-demo#39]
I try to run this app in my android device, but it crashed. So i want to change the mini batch to 1 in deploy.prototxt, but i i can't find a parameter that called mini batch.

**Comment by sh1r0** [comment]
Please refer to https://github.com/sh1r0/caffe-android-demo/issues/33#issuecomment-243024604.

**Comment by wumangxing1990** [comment]
thanks, but after i change the mini batch to 1, it still can't run . When i click the app, it crash.

**Comment by sh1r0** [comment]
Any logs?

**Comment by sh1r0** [comment]
see #40
