### ISSUE TITLE
How to Load Model File --Model file cannot be loaded

### ISSUE THREAD

**Issue by gopi1989** [sh1r0/caffe-android-demo#4]
I have a model file, the file cannot be loaded. Model file look like this 

layer {
  name: "data"
  type: "MemoryData"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }

  memory_data_param {
   batch_size: 1
   channels: 3
   height: 48
   width: 64
  }
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1.0
  }
  param {
    lr_mult: 2.0
  }
  convolution_param {
    num_output: 20
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}

I passing path from android to jni. Path look like /storage/emulated/0/Download/smile_deploy.prototxt.
I have an issue in that line:
caffe_net = new Net<float>(model_path, caffe::TEST);

Thank you

**Comment by sh1r0** [comment]
Hi, I just updated this project with the latest caffe-android-lib (https://github.com/sh1r0/caffe-android-lib/commit/2c0d60bfd4eb1d698770fc2d075cf7d9d5fe6472) which basically is based on up-to-date caffe (https://github.com/BVLC/caffe/commit/03a84bf464dd47bcec9ac943f0229a758c627f05). Now, you can simply define the input size of your model like in deploy.prototxt without using MemoryDataLayer.
If you are still interested in this project, you might wanna try it, and please let me know if there are any problems.
Thanks.
