### ISSUE TITLE
jnilibs issue

### ISSUE THREAD

**Issue by chaituNova** [sh1r0/caffe-android-demo#44]
A month ago, I downloaded your code and was able to sucessfully use it in the android device. Then few days back, I updated the android/gradle version from 2.1.0 to 2.1.2. Then onwards the following error is coming :  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "sigfillset" referenced by "libcaffe.so"...

After that I even re downloaded it and compiled but no success. The android studio version that I am trying is the following. Could you tell me if I am using a higher version. Also, did you create the jnilibs using caffe-android-libs git repo?
![image](https://cloud.githubusercontent.com/assets/19497297/20381396/4bb30f74-ac75-11e6-9df1-14dd97a29720.png)

**Comment by sh1r0** [comment]
First, please refer to https://github.com/sh1r0/caffe-android-demo/issues/40#issuecomment-256854306. And yes, this project is for demonstrating caffe-android-lib, btw, the prebuilt libs in this project are outdated.

**Comment by chaituNova** [comment]
Thanks for your reply :) I forgot to check in the closed issues
