### ISSUE TITLE
Can't open the app

### ISSUE THREAD

**Issue by nerddd** [sh1r0/caffe-android-demo#48]
hey,I have some trouble in running the application.The android version of my phone is 4.4.4，I've moved the .caffemodel and deploy.prototxt under /sdcard/caffe_mobile/bvlc_reference_caffenet，and installed the apk on my phone successfully.But when I ran the app,it crashed...Here is my logcat,any suggestion will be appreciated!

> E/AndroidRuntime: FATAL EXCEPTION: main
>                   Process: com.sh1r0.caffe_android_demo, PID: 7466
>                   java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "sigfillset" referenced by "libcaffe.so"...
>                       at java.lang.Runtime.loadLibrary(Runtime.java:364)
>                       at java.lang.System.loadLibrary(System.java:526)
>                       at com.sh1r0.caffe_android_demo.MainActivity.<clinit>(MainActivity.java:57)
>                       at java.lang.Class.newInstanceImpl(Native Method)
>                       at java.lang.Class.newInstance(Class.java:1208)
>                       at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
>                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2109)
>                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2241)
>                       at android.app.ActivityThread.access$800(ActivityThread.java:141)
>                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
>                       at android.os.Handler.dispatchMessage(Handler.java:102)
>                       at android.os.Looper.loop(Looper.java:136)
>                       at android.app.ActivityThread.main(ActivityThread.java:5049)
>                       at java.lang.reflect.Method.invokeNative(Native Method)
>                       at java.lang.reflect.Method.invoke(Method.java:515)
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
>                       at dalvik.system.NativeStart.main(Native Method)
> Application terminated.

**Comment by sh1r0** [comment]
Please refer to https://github.com/sh1r0/caffe-android-demo/issues/40#issuecomment-256854306, thanks.

**Comment by nerddd** [comment]
what if I update the api version to 23?

**Comment by sh1r0** [comment]
Should be fine.

**Comment by nerddd** [comment]
Oh，thank you very much
