### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by NRmf** [sh1r0/caffe-android-demo#5]
I am new to Android development and I've been trying to run the demo on eclipse.

I get the following err:

08-06 13:55:34.822: E/AndroidRuntime(23010): FATAL EXCEPTION: main
08-06 13:55:34.822: E/AndroidRuntime(23010): Process: com.sh1r0.caffe_android_demo, PID: 23010
08-06 13:55:34.822: E/AndroidRuntime(23010): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.sh1r0.caffe_android_demo/com.sh1r0.caffe_android_demo.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.sh1r0.caffe_android_demo.MainActivity" on path: DexPathList[[zip file "/data/app/com.sh1r0.caffe_android_demo-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.sh1r0.caffe_android_demo-1, /vendor/lib, /system/lib]]
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2131)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at android.app.ActivityThread.access$800(ActivityThread.java:142)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at android.os.Looper.loop(Looper.java:136)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at android.app.ActivityThread.main(ActivityThread.java:5118)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at java.lang.reflect.Method.invoke(Method.java:515)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at dalvik.system.NativeStart.main(Native Method)
08-06 13:55:34.822: E/AndroidRuntime(23010): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sh1r0.caffe_android_demo.MainActivity" on path: DexPathList[[zip file "/data/app/com.sh1r0.caffe_android_demo-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.sh1r0.caffe_android_demo-1, /vendor/lib, /system/lib]]
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2122)
08-06 13:55:34.822: E/AndroidRuntime(23010): 	... 11 more

**Comment by sh1r0** [comment]
This is basically a project of android studio.
