### ISSUE TITLE
File not found 

### ISSUE THREAD

**Issue by DushyantMainwal** [sh1r0/caffe-android-demo#50]
I'm getting a file not found error..

Check failed: fd != -1 (-1 vs. -1) File not found: /storage/emulated/0/caffe_mobile/plantClassification/weights.caffemodel

**Comment by billygl** [comment]
have you checked this
https://github.com/sh1r0/caffe-android-demo/issues/41 ?

**Comment by DushyantMainwal** [comment]
Permissions are working fine..
Can you tell me why it looks for the files in _plantClassification_ folder and not in the pushed bvlc_reference_caffenet folder??
After making the folder plantClassification and moving the 4 files(deploy.ptototxt, readme.md, solver.prototxt,  train_val_prototxt) it shows..
Check failed: fd != -1 (-1 vs. -1) File not found: /storage/emulated/0/caffe_mobile/plantClassification/weights.caffemodel
why does it asks for weights.caffemodel??

In lower API (18) it gives an UnsatisfiedLinkError..
cannot locate symbol "sigfillset" referenced by "libcaffe.so"..

**Comment by sh1r0** [comment]
@DushyantMainwal Did you do a fresh clone of this repository or make any modification? As for API version issue, please refer to https://github.com/sh1r0/caffe-android-demo/issues/40#issuecomment-256854306.

**Comment by DushyantMainwal** [comment]
Here's what I did:
->Cloned the BVLC/caffe.git
->Downloaded the bvlc_reference_caffenet.caffemodel(232mb) from readme.md because ./scripts/download_model_binary.py wasn't working
->pushed the files from models/bvlc_reference_caffenet/ into  /sdcard/caffe_mobile/bvlc_reference_caffenet/ (all 5 files)
-> After that I cloned this (caffe-android-demo) project
-> and then build the project successfully (except it coludn't resolve the JNI fuctions in CaffeMobile.java)
-> but when I tried to ran the project into my phone, it shows the error..
Check failed: fd != -1 (-1 vs. -1) File not found: /storage/emulated/0/caffe_mobile/plantClassification/deploy.prototxt
-> For some reason it was looking for the files in plantClassification folder
-> Then I made the plantClassification folder in my /sdcard/ and moved all 5 files into it
-> After running the project again, it shows ..
Check failed: fd != -1 (-1 vs. -1) File not found: /storage/emulated/0/caffe_mobile/plantClassification/weights.caffemodel

**Comment by sh1r0** [comment]
@DushyantMainwal I think you cloned the forked one (https://github.com/sippel93/caffe-android-demo) instead of this repo.

**Comment by DushyantMainwal** [comment]
@sh1r0 I forked the repo again and it worked, Thank you for the solution
Before closing this issue can you tell why does it gives a warning can't resolve JNI functions and still uses a native function for loading the models, and can you please provide me a link for using custom trained model.
Thanks again for your time

**Comment by sh1r0** [comment]
@DushyantMainwal 
1. If you got any warnings about jni, please check your api level and the abi of your target device.
2. You could modify the model loading part to meet your need.
