### ISSUE TITLE
Use my model files instead of your  files.

### ISSUE THREAD

**Issue by thinkerzhangyan** [sh1r0/caffe-android-demo#52]
I use my bvlc_reference_caffenet.caffemodel and deploy.prototoxt instead of your  bvlc_reference_caffenet.caffemodel and deploy.prototoxt in the project,but when I run the project it report error。

Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: /storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/flower/bvlc_reference_caffenet.caffemodel。

**Comment by sh1r0** [comment]
How did you get/train your model? I'm afraid that the version of caffe you use is newer than the built one.

**Comment by sh1r0** [comment]
Hi @946898963, any updates?
