### ISSUE TITLE
fatal exception : couldn't find "libcaffe.so"

### ISSUE THREAD

**Issue by zobyltomok** [sh1r0/caffe-android-demo#53]
Hello,
i'm trying your application on a non rooted nexus 7 (android 5.1.1) and the application crashed due to the following exception : 
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.sh1r0.caffe_android_demo/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.sh1r0.caffe_android_demo/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.sh1r0.caffe_android_demo/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.sh1r0.caffe_android_demo/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.sh1r0.caffe_android_demo/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.sh1r0.caffe_android_demo/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.sh1r0.caffe_android_demo/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.sh1r0.caffe_android_demo/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.sh1r0.caffe_android_demo/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.sh1r0.caffe_android_demo/files/instant-run/dex/slice-slice_0-classes.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib, /system/lib]]] couldn't find "libcaffe.so"

Does your application needs a rooted android phone ?
It works fine on a rooted redmi 3.
Do you have any idea of what's wrong ?
Thanks.

**Comment by sh1r0** [comment]
No, it does not require a rooted device. However, libcaffe is pre-built for only 2 kinds of abis, x86_64 and arm64-v8a. You could build arm-v7a version on your own, thanks.

**Comment by zobyltomok** [comment]
ok. Thank you for your answer.
