### ISSUE TITLE
 dlopen("/data/app/com.sh1r0.caffe_android_demo_1_garbage-1/lib/arm64/libcaffe_jni.so", RTLD_LAZY) failed: dlopen failed: could not load library "libcaffe.so.1.0.0-rc3" needed by "/data/app/com.sh1r0.caffe_android_demo_1_garbage-1/lib/arm64/libcaffe_jni.so"; caused by library "libcaffe.so.1.0.0-rc3" not found

### ISSUE THREAD

**Issue by gjtjx** [sh1r0/caffe-android-demo#55]
my cmake version is 3.4.0 ，build successed and the lib is libcaffe.so libcaffe.so.1.0.0-rc3 libcaffe_jni.so libproto.a，when run on snapdragon 652，error "libcaffe.so.1.0.0-rc3" not found，needs chmod 777？
and why you build lib just have  libcaffe.so  libcaffe_jni.so ？any suggest？

**Comment by sh1r0** [comment]
This project is for demonstrating how to use [caffe-android-lib](https://github.com/sh1r0/caffe-android-lib) which means that building caffe executable is not the main focus.
