### ISSUE TITLE
How to ndk build .so files for ABI x86 or arm_v7?

### ISSUE THREAD

**Issue by ventusff** [sh1r0/caffe-android-demo#56]
It seems that in the jniLibs Folder there is only ABIs .so for arm_v8 and x86_64;
I'm wondering whether it's possible to create .so files for ABI x86 or arm_v7 and how?
I've tried to compile the caffe-android-lib on my ubuntu system and quite sure that I have enough preques. but just keep failing and get all kinds of errors;
and still how can I ndk those caffe_model.cpp and caffe_jni.cpp?

**Comment by sh1r0** [comment]
Hi @ventusff, please provide more information about your build environment, such as OS, cmake version, NDK version, etc. Thanks.

**Comment by sh1r0** [comment]
Hi @ventusff, please refer to https://github.com/sh1r0/caffe-android-lib/issues/100, thanks.
