### ISSUE TITLE
Crash in Samsung S7 with Android 7

### ISSUE THREAD

**Issue by gabrielssimoes** [sh1r0/caffe-android-demo#57]
Hello

Did you know why the code crash over Samsung S7 with android 7? The error points to a missing file, but file is stil there. :/

io.cpp:36] Check failed: fd != -1 (-1 vs. -1) File not found: /storage/emulated/0/c...

Thanks!

**Comment by billygl** [comment]
Check this out
Issue #41

**Comment by gabrielssimoes** [comment]
It works!

Thank you and sorry for the duplication!
