### ISSUE TITLE
Demo stops

### ISSUE THREAD

**Issue by NRmf** [sh1r0/caffe-android-demo#6]
The app runs on the device (Nexus 6), but when I select an image or take a photo I see the (Predicting ..) dialog, but then the app exits and I get a (Unfortunately, Caffe-Android-Demo has stopped). 

Any help on what's going wrong?

**Comment by NRmf** [comment]
Figured out I had an error in pushing the files to the device!
Works well now.

Thanks

**Comment by mongoose54** [comment]
@NRmf How did you push the files to your device? What commands? I am running into the same problem. Thanks!

**Comment by nmfelemban** [comment]
@mongoose54 Following the instruction on this page: https://github.com/sh1r0/caffe-android-lib#usage

./get_model.py
adb shell mkdir -p /sdcard/caffe_mobile/
adb push caffe-mobile/jni/caffe/models/bvlc_reference_caffenet/ /sdcard/caffe_mobile/bvlc_reference_caffenet/
