### ISSUE TITLE
can not run project,...File not found

### ISSUE THREAD

**Issue by wakeee** [sh1r0/caffe-android-demo#61]
**i run this project but got error, the apk stop immediately**
the caffe-jni.so file can not find the proto file , but i check it on java and print it, it shows the file exists! 

        Log.d(LOG_TAG, modelProto);
        Log.d(LOG_TAG, modelBinary);
        File filename = new File(modelProto);
        if (filename.exists()) {
            Log.d(LOG_TAG, modelProto+" exist!!!!");
        }

**logcat are as follow:**

1 16371-16371/? I/zygote64: Late-enabling -Xcheck:jni
10-26 15:54:33.839 16371-16371/? I/zygote64: Reinit property: 
dalvik.vm.checkjni= false
10-26 15:54:33.848 16371-16371/? D/ActivityThread: 
ActivityThread,attachApplication
10-26 15:54:33.871 16371-16371/? W/ActivityThread: Application 
com.sh1r0.caffe_android_demo is waiting for the debugger on port 8100...
10-26 15:54:33.875 16371-16371/? I/System.out: Sending WAIT chunk
10-26 15:54:34.873 16371-16378/com.sh1r0.caffe_android_demo I/zygote64: 
Debugger is active
10-26 15:54:34.880 16371-16371/com.sh1r0.caffe_android_demo I/System.out: 
Debugger has connected
10-26 15:54:34.880 16371-16371/com.sh1r0.caffe_android_demo I/System.out: 
waiting for debugger to settle...
10-26 15:54:35.080 16371-16371/com.sh1r0.caffe_android_demo I/System.out: 
waiting for debugger to settle...
10-26 15:54:35.280 16371-16371/com.sh1r0.caffe_android_demo I/System.out: 
waiting for debugger to settle...
10-26 15:54:35.482 16371-16371/com.sh1r0.caffe_android_demo I/System.out: 
waiting for debugger to settle...
10-26 15:54:35.682 16371-16371/com.sh1r0.caffe_android_demo I/System.out: 
waiting for debugger to settle...
10-26 15:54:35.883 16371-16371/com.sh1r0.caffe_android_demo I/System.out: 
waiting for debugger to settle...
10-26 15:54:36.084 16371-16371/com.sh1r0.caffe_android_demo I/System.out: 
waiting for debugger to settle...
10-26 15:54:36.485 16371-16371/com.sh1r0.caffe_android_demo I/System.out: 
debugger has settled (1435)
10-26 15:54:36.502 16371-16371/com.sh1r0.caffe_android_demo D/HwFLClassLoader: 
get used feature list :/feature/used-list failed!
10-26 15:54:36.503 16371-16371/com.sh1r0.caffe_android_demo D/HwFLClassLoader: 
USE_FEATURE_LIST had not init! 
10-26 15:54:36.505 16371-16371/com.sh1r0.caffe_android_demo W/cutils-trace: 
Truncated name in atrace_begin_body: /data/app/com.sh1r0.caffe_android_demo-
lgNN409G3yuENefCXcrTwA==/base.apk:/data/app/com.sh1r0.caffe_android_demo-
lgNN409G3yuENefCXcrTwA==/split_lib_dependencies_apk.apk:/data/app/com.sh1r0.caf
fe_android_demo-
lgNN409G3yuENefCXcrTwA==/split_lib_slice_0_apk.apk:/data/app/com.sh1r0.caffe_an
droid_demo-
lgNN409G3yuENefCXcrTwA==/split_lib_slice_1_apk.apk:/data/app/com.sh1r0.caffe_an
droid_demo-
lgNN409G3yuENefCXcrTwA==/split_lib_slice_2_apk.apk:/data/app/com.sh1r0.caffe_an
droid_demo-
lgNN409G3yuENefCXcrTwA==/split_lib_slice_3_apk.apk:/data/app/com.sh1r0.caffe_an
droid_demo-
lgNN409G3yuENefCXcrTwA==/split_lib_slice_4_apk.apk:/data/app/com.sh1r0.caffe_an
droid_demo-
lgNN409G3yuENefCXcrTwA==/split_lib_slice_5_apk.apk:/data/app/com.sh1r0.caffe_an
droid_demo-
lgNN409G3yuENefCXcrTwA==/split_lib_slice_6_apk.apk:/data/app/com.sh1r0.caffe_an
droid_demo-
lgNN409G3yuENefCXcrTwA==/split_lib_slice_7_apk.apk:/data/app/com.sh1r0.caffe_an
droid_demo-lgNN409G3yuENefCXcrTwA==/split_lib_slice_8_apk.apk:/data/ap
10-26 15:54:36.629 16371-16371/com.sh1r0.caffe_android_demo I/InstantRun: 
starting instant run server: is main process
10-26 15:54:36.636 16371-16371/com.sh1r0.caffe_android_demo E/Minikin: Could 
not get cmap table size!
10-26 15:54:36.683 16371-16371/com.sh1r0.caffe_android_demo I/HwCust: 
Constructor found for class android.app.HwCustActivityImpl
10-26 15:54:36.683 16371-16371/com.sh1r0.caffe_android_demo D/HwCust: Create 
obj success use class android.app.HwCustActivityImpl
10-26 15:54:36.692 16371-16371/com.sh1r0.caffe_android_demo I/HwCust: 
Constructor found for class android.app.HwCustHwWallpaperManagerImpl
10-26 15:54:36.692 16371-16371/com.sh1r0.caffe_android_demo D/HwCust: Create 
obj success use class android.app.HwCustHwWallpaperManagerImpl
10-26 15:54:36.714 16371-16371/com.sh1r0.caffe_android_demo 
D/HwGalleryCacheManagerImpl: mIsEffect:false
10-26 15:54:36.716 16371-16371/com.sh1r0.caffe_android_demo 
D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, 
mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
10-26 15:54:36.717 16371-16371/com.sh1r0.caffe_android_demo 
D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, 
mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
10-26 15:54:36.717 16371-16371/com.sh1r0.caffe_android_demo 
D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, 
mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
10-26 15:54:36.718 16371-16371/com.sh1r0.caffe_android_demo 
D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, 
mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
10-26 15:54:36.740 16371-16371/com.sh1r0.caffe_android_demo I/Utils: 
Utils_isSuperResolutionSupport [load libai_client.success]
10-26 15:54:36.782 16371-16371/com.sh1r0.caffe_android_demo D/HwRTBlurUtils: 
check blur style for HwPhoneWindow-, themeResId : 0x7f060000, context : 
com.sh1r0.caffe_android_demo.MainActivity@9ddfaba, Nhwext : 0, get Blur : 
disable with , null
10-26 15:54:36.783 16371-16371/com.sh1r0.caffe_android_demo 
W/WindowDecorActionBar: should not do the transition or the transition anim is 
null or it is running or the mContainer view is null or mContainer view hasn't 
been drawn to screen 
10-26 15:54:36.784 16371-16371/com.sh1r0.caffe_android_demo E/HwResourcesImpl: 
readDefaultConfig : FileNotFoundException
10-26 15:54:36.788 16371-16371/com.sh1r0.caffe_android_demo I/HwCust: 
Constructor found for class android.content.res.HwCustHwResourcesImpl
10-26 15:54:36.788 16371-16371/com.sh1r0.caffe_android_demo D/HwCust: Create 
obj success use class android.content.res.HwCustHwResourcesImpl
10-26 15:54:36.813 16371-16371/com.sh1r0.caffe_android_demo D/CaffeDemo: 
/storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/deploy.prototxt
10-26 15:54:36.813 16371-16371/com.sh1r0.caffe_android_demo D/CaffeDemo: 
/storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/bvlc_reference_caffene
t.caffemodel

        10-26 15:54:36.813 16371-16371/com.sh1r0.caffe_android_demo D/CaffeDemo: 
        /storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/deploy.prototxt 
        exist!!!!

        10-26 15:54:36.814 16371-16371/com.sh1r0.caffe_android_demo A/caffe_jni: F1026 
        15:54:36.814195 16371 io.cpp:36] Check failed: fd != -1 (-1 vs. -1) File not 
        found: /storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/deploy.prototxt

        10-26 15:54:36.814 16371-16371/com.sh1r0.caffe_android_demo A/caffe_jni: 
        terminating.

10-26 15:54:36.815 16371-16371/com.sh1r0.caffe_android_demo A/libc: Fatal 
signal 6 (SIGABRT), code -6 in tid 16371 (fe_android_demo)

**Comment by sh1r0** [comment]
Please refer to https://github.com/sh1r0/caffe-android-demo/issues/41#issuecomment-264628393.
