### ISSUE TITLE
ImportError: No module named yaml

### ISSUE THREAD

**Issue by suesunna** [sh1r0/caffe-android-demo#63]
./scripts/download_model_binary.py models/bvlc_reference_caffenet/
Traceback (most recent call last):
  File "./scripts/download_model_binary.py", line 5, in <module>
    import yaml
ImportError: No module named yaml

我安装了yaml但是还是不行，求赐教
pip install pyyaml

**Comment by sh1r0** [comment]
This issue is more about caffe setup, please check your python version and also refer to <http://caffe.berkeleyvision.org/installation.html#prerequisites> and <https://github.com/BVLC/caffe/blob/master/python/requirements.txt>. I'll close the issue, thanks.
