### ISSUE TITLE
File not found: /storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/deploy.prototxt

### ISSUE THREAD

**Issue by suesunna** [sh1r0/caffe-android-demo#64]
I have a test,it shows this file is exists,but caffe_jni shows not found.
------------------
 Log.e("songxy", "modelProto = " + modelProto);
        File file = new File(modelProto);
        if(file.exists()){
            Log.e("songxy", "exists");
        }else{
            Log.e("songxy", "not exists");
        }

04-24 15:36:34.998 8147-8147/com.sh1r0.caffe_android_demo E/songxy: modelProto = /storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/deploy.prototxt
04-24 15:36:34.999 8147-8147/com.sh1r0.caffe_android_demo E/songxy: # exists
04-24 15:36:34.999 8147-8147/com.sh1r0.caffe_android_demo A/caffe_jni: F0424 15:36:34.999740  8147 io.cpp:36] Check failed: fd != -1 (-1 vs. -1) File not found: /storage/emulated/0/caffe_mobile/bvlc_reference_caffenet/deploy.prototxt
04-24 15:36:34.999 8147-8147/com.sh1r0.caffe_android_demo A/caffe_jni: terminating.
04-24 15:36:35.000 8147-8147/com.sh1r0.caffe_android_demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 8147 (fe_android_demo)

**Comment by suesunna** [comment]
I have solved this problem, I use LeMax2, android 6.0.1 , in application setting ,open Storage permissions. Please close this issues,thank you

**Comment by sh1r0** [comment]
Hi @suesunna, this issue is a duplicate and the solution is commented in #41. BTW, you could close this on your own.
