### ISSUE TITLE
How to get customize caffemodel working?

### ISSUE THREAD

**Issue by buttonzzj** [sh1r0/caffe-android-demo#7]
Hi,

First of all, thanks for this amazing app!
I have trained a caffe model with CIFAR-10 data set and would like to see it's performance using the mobile app.

The prototxt file was like:
name: "CIFAR10_quick_test"
input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 32
  dim: 32
}
layer { ...// layers ....}

I modified the header according to the deploy_mobile.prototxt as:
name: "CIFAR10_quick_test"
input: "data"
layer {
  name: "data"
  type: "MemoryData"
  top: "data"
  top: "label"
  memory_data_param {
    batch_size: 1
    channels: 3
    height: 32
    width: 32
  }
  transform_param {
    crop_size: 32
    mean_value: 104
    mean_value: 117
    mean_value: 123
    mirror: false
  }
}
layer { .... // layers ...}

But then I got this fault running the app:
10-05 00:53:46.930 16636-16636/com.sh1r0.caffe_android_demo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 16636 (fe_android_demo)
10-05 00:53:46.930 16636-16636/com.sh1r0.caffe_android_demo W/libc: Security Level: (1), Debug inforamtion is controlled by the DUMPABLE flag.

What am I missing?

Thank you so much for your help!

**Comment by mongoose54** [comment]
Same error here. I am trying to run the demo with default model using Android Studio 1.4 on my device and here is the output:

```
10-09 15:47:29.052 22192-22212/com.sh1r0.caffe_android_demo D/stderr: Copying source layer 
10-09 15:47:29.052 22192-22212/com.sh1r0.caffe_android_demo D/stderr: fc6
10-09 15:47:29.052 22192-22212/com.sh1r0.caffe_android_demo D/stderr: [
10-09 15:47:29.053 22192-22212/com.sh1r0.caffe_android_demo D/stderr: ERROR
10-09 15:47:29.053 22192-22212/com.sh1r0.caffe_android_demo D/stderr: ]	
10-09 15:47:29.053 22192-22212/com.sh1r0.caffe_android_demo D/stderr: (target_blobs.size()) == (source_layer.blobs_size())
10-09 15:47:29.053 22192-22212/com.sh1r0.caffe_android_demo D/stderr: Incompatible number of blobs for layer 
10-09 15:47:29.053 22192-22212/com.sh1r0.caffe_android_demo D/stderr: fc6
10-09 15:47:29.209 22192-22192/com.sh1r0.caffe_android_demo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x40 in tid 22192 (fe_android_demo)
```

@buttonzzj Have you managed to run the demo with default model?

**Comment by sh1r0** [comment]
Hey guys, I just updated this project with the latest caffe-android-lib (https://github.com/sh1r0/caffe-android-lib/commit/2c0d60bfd4eb1d698770fc2d075cf7d9d5fe6472) which basically is based on up-to-date caffe (https://github.com/BVLC/caffe/commit/03a84bf464dd47bcec9ac943f0229a758c627f05). If any of you are still interested in this project, you might wanna try it, and please let me know if there are any problems.
Thanks.
