### ISSUE TITLE
deploy_mobile.prototxt using mean pixel?

### ISSUE THREAD

**Issue by duyhtq** [sh1r0/caffe-android-demo#9]
hi.  i'm looking at your example.  it looks like during training in train_val.prototxt you use mean_file (mean image), while on mobile in deploy_mobile.prototxt you use mean_value (mean pixel).  why is that?  why don't you use both mean image at both places?  thanks.

**Comment by sh1r0** [comment]
In short, for convenience. I hope to simplify things you need to prepare for a quick demo, that is, the model definition (prototxt) and its binary file (caffemodel). But actually, you can use either way for your preference. And I just "added" that deploy_mobile.prototxt for showing that.

**Comment by duyhtq** [comment]
understood.  but can you mix them up like that (i.e. using mean image during training and mean pixel during prediction on mobile)?   or do you must use mean image in both training and prediction OR use mean pixel in both training and prediction?

**Comment by sh1r0** [comment]
It should not be a big problem for testing, if you still have concerns you can stick with either way.

**Comment by duyhtq** [comment]
cool, thanks.
